# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-stretch
        environment: # environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle

    steps:
      - checkout

      - run:
          name: Configuring Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(tail -1 Gemfile.lock | xargs)' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler -v $BUNDLER_VERSION

      # Load installed gems from cache if possible, bundle install & clean,
      # then save cache. Multiple caches to increase the chance of a cache hit.
      # => Make sure to specify ruby version & architecture in cache keys
      #    (or conflicts on native gems may appear)
      - restore_cache:
          keys:
            - v1-gem-cache-ruby-2.6-{{ arch }}-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache-ruby-2.6-{{ arch }}-

      - run:
          name: Install dependencies
          command: bundle check --path vendor/bundle || bundle install --deployment

      - save_cache:
          key: v1-gem-cache-ruby-2.6-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Run tests!
      - run:
          name: Run tests
          command: make test
